require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  Exclude:
    - bin/*
    - db/schema.rb
  NewCops: enable

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 50

RSpec/MultipleMemoizedHelpers:
  Enabled: false

Metrics/BlockLength:
  Max: 100

Lint/MissingSuper:
  Enabled: false

RSpec/Rails/InferredSpecType:
  Enabled: false

RSpecRails/InferredSpecType:
  Enabled: false

RSpec/EmptyExampleGroup:
  Enabled: false